name = "molip-task-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
NOTION_DATABASE_ID = ""
RESPONSE_TYPE = "in_channel"

# Secrets (set via `wrangler secret put`):
# SLACK_SIGNING_SECRET
# SLACK_BOT_TOKEN
# NOTION_API_TOKEN
